image:
  file: .gitpod.dockerfile

tasks:
  - name: initialize
    before: |

      echo "🚀"

    init: |
      
      # ------------------------------------
      # Install sat
      # ------------------------------------
      git clone https://github.com/suborbital/sat.git
      cd sat
      make sat
      cp .bin/sat ../executors
      cd ..
      rm -rf sat

      # ------------------------------------
      # Build Venusia Registry 
      # ------------------------------------
      cd venusia-registry
      go build

      cd certs
      ./generate.sh
      cd ../..

      # ------------------------------------
      # Build Alcor Reverse-Proxy
      # ------------------------------------
      cd alcor-reverse-proxy
      go build

      cd certs
      ./generate.sh
      cd ../..

      # ------------------------------------
      # Build Procyon
      # ------------------------------------
      go build



ports:
    # Alcor reverse proxy 
  - port: 8080
    visibility: public
# Procyon
  - port: 9090
    visibility: public
# Venusia Registry
  - port: 9999
    visibility: public

vscode:
  extensions:
    - wayou.vscode-todo-highlight
    - pkief.material-icon-theme
    - golang.go
    - bpruitt-goddard.mermaid-markdown-syntax-highlighting
    - bierner.markdown-mermaid
    - grain-lang.vscode-grain
    - rust-lang.rust
