---
image:
  file: .gitpod.dockerfile

tasks:
  - name: initialize
    before: |

      # ------------------------------------
      # GoLang
      # ------------------------------------

      #source /home/gitpod/.gvm/scripts/gvm
      #gvm use go1.17.5

      #sudo echo "source /home/gitpod/.gvm/scripts/gvm" >> $HOME/.bashrc
      #sudo echo "gvm use go1.17.5" >> $HOME/.bashrc

      # ------------------------------------
      # Mkcert
      # ------------------------------------
      sudo apt-get update
      sudo apt install libnss3-tools -y
      brew install mkcert


    init: |

      # ------------------------------------
      # Install the Suborbital CLI
      # ------------------------------------
      brew tap suborbital/subo
      brew install subo
      
      # ------------------------------------
      # Install sat
      # ------------------------------------
      git clone https://github.com/suborbital/sat.git
      cd sat
      make sat
      cp .bin/sat ../executors
      cd ..
      rm -rf sat

      # ------------------------------------
      # Install Venusia Registry 
      # (with samples)
      # ------------------------------------
      git clone --depth=1 https://github.com/bots-garden/venusia.git
      cd venusia
      go build

      cd certs
      ./generate.sh
      cd ../..

      # ------------------------------------
      # Install Galago Wasm Executor
      # ------------------------------------
      #git clone --depth=1 https://gitlab.com/k33g_org/side-projects/galago/galago-executor.git
      #cd galago-executor
      #go build
      #cd ..

ports:
  - port: 8080
    visibility: public
  - port: 8888
    visibility: public
  - port: 3000
    visibility: public
  - port: 9090
    visibility: public
  - port: 9999
    visibility: public

vscode:
  extensions:
    - wayou.vscode-todo-highlight
    - pkief.material-icon-theme
    - golang.go
    - bpruitt-goddard.mermaid-markdown-syntax-highlighting
    - bierner.markdown-mermaid
