image:
  file: .gitpod.dockerfile

tasks:
  - name: initialize
    before: |

      echo "🚀"

    init: |
      
      go install github.com/spf13/cobra-cli@latest

      # ------------------------------------
      # Install sat
      # ------------------------------------
      git clone https://github.com/suborbital/sat.git
      cd sat
      make sat
      cp .bin/sat ../procyon-launcher/executors
      cd ..
      rm -rf sat

      # ------------------------------------
      # Build Procyon Reverse-Proxy
      # ------------------------------------
      cd procyon-reverse-proxy
      go build

      #cd certs; ./generate.sh; cd ..
      
      cd ..

      # ------------------------------------
      # Build Procyon Launcher
      # ------------------------------------
      cd procyon-launcher
      go build
      cd ..

      # ------------------------------------
      # Prepare Procyon registry
      # ------------------------------------
      cd procyon-registry
      npm install
      cd certs; ./generate.sh; cd ../..




ports:
    # Alcor reverse proxy 
  - port: 8080
    visibility: public
# Procyon
  - port: 9090
    visibility: public
# Venusia Registry
  - port: 9999
    visibility: public

vscode:
  extensions:
    - pkief.material-icon-theme
    - golang.go
    - rust-lang.rust
    - aaron-bond.better-comments
    - grain-lang.vscode-grain
#    - bpruitt-goddard.mermaid-markdown-syntax-highlighting
#    - bierner.markdown-mermaid
