#!/bin/bash
: '
---------------------------------------------------
 Procyon CLI: procyonctl
---------------------------------------------------
'

PROCYONCTL_VERSION="0.0.1"
# ------------------------------------
# procyonctl
# ------------------------------------
eval $(cat $(dirname "$0")/procyon.config)

if [[ "$1" == "version" ]]; then
  echo "procyonctl v${PROCYONCTL_VERSION}"
  exit 0
fi

if [[ "$1" == "help" ]]; then
  echo "🚧 work in progress"
  exit 0
fi

if [[ "$1" == "url" ]]; then
  echo "🌍 procyon url: ${PROCYON_URL}"
  exit 0
fi

: '
---------------------------------------------------
 Procyon task
---------------------------------------------------
Procyon is a Sat orchestrator
Commands:
- procyonctl task deploy k33g/forty-two/1.0.0/forty-two.wasm forty-two rev1
  procyonctl task deploy k33g/hello-world/1.0.1/hello-world.wasm hello-world rev1
- procyonctl task list
- procyonctl task info a6419ab3-fbe4-4f5e-92ea-c832d8869090
- procyonctl task switch-revision a6419ab3-fbe4-4f5e-92ea-c832d8869090
- procyonctl task kill a6419ab3-fbe4-4f5e-92ea-c832d8869090
  TODO: update task list when remove
- procyonctl task help
- procyonctl task switch-func-revision forty-two rev1
- procyonctl task switch-func-revision hello-world rev1

'

#function procyon_switch_revision() {
#  function_name=$1
#  function_revision=$2
#  url=${ALCOR_URL}/revisions/${function_name}/${function_revision}
#  echo "🍊 ${url}"
#  curl "${ALCOR_URL}/revisions/${function_name}/${function_revision}"; echo ""
#}

function procyon_task_deploy() {
  wasm_file=$1
  function_name=$2
  function_revision=$3
  curl -v --request POST \
  --header 'Content-Type: application/json' \
  --data '{
      "executor": 1,
      "wasmFileName": "'"${wasm_file}"'",
      "wasmRegistryUrl": "'"${WASM_REGISTRY_URL}/${wasm_file}"'",
      "functionName": "'"${function_name}"'",
      "functionRevision": "'"${function_revision}"'",
      "defaultRevision": false
    }
  ' ${PROCYON_URL}/tasks
}

if [[ "$1" == "task" ]]; then

  if [[ "$2" == "help" ]]; then
    echo "🚧 work in progress"
    exit 0
  fi

  if [[ "$2" == "list" ]]; then
    curl ${PROCYON_URL}/tasks
    exit 0
  fi

  if [[ "$2" == "kill" ]]; then
    task_id=$3
    curl -v --request DELETE ${PROCYON_URL}/tasks/${task_id}
    exit 0
  fi

  if [[ "$2" == "info" ]]; then
    task_id=$3
    curl -v --request GET ${PROCYON_URL}/tasks/${task_id}
    exit 0
  fi

  
  if [[ "$2" == "switch-revision" ]]; then
    task_id=$3
    curl -v --request PUT ${PROCYON_URL}/tasks/${task_id}
    echo "🌍 ${PROCYON_URL}/tasks/${task_id}"
    exit 0
  fi

  if [[ "$2" == "set-default-revision" ]]; then
    functionName=$3
    functionRevision=$4
    switch=$5
    curl -v --request PUT ${PROCYON_URL}/revisions/${functionName}/${functionRevision}/default/${switch}
    exit 0
  fi

  if [[ "$2" == "deploy" ]]; then
    wasm_file=$3
    function_name=$4
    function_revision=$5
    procyon_task_deploy ${wasm_file} ${function_name} ${function_revision}
    exit 0
  fi

  echo "🤔 please try again, I don't understand"
fi


: '
---------------------------------------------------
 Procyon func
---------------------------------------------------
Procyon is a Sat orchestrator
Commands:
- procyonctl func post hello 'Jane Doe'
- procyonctl func post-revision hello rev1 'John Doe'

- procyonctl func get forty-two
- procyonctl func get-revision hello-world rev1

- procyonctl func list
- procyonctl func help
'

function procyon_func_post() {
  function_name=$1
  data=$2
  curl -X POST -d ${data} ${ALCOR_URL}/functions/${function_name}; echo ""
}

function procyon_func_post_rev() {
  function_name=$1
  function_revision=$2
  data=$3
  curl -X POST -d ${data} ${ALCOR_URL}/functions/${function_name}/${function_revision}; echo ""
}

function procyon_func_get() {
  function_name=$1
  curl ${ALCOR_URL}/functions/${function_name}; echo ""
}

function procyon_func_get_rev() {
  function_name=$1
  function_revision=$2
  curl ${ALCOR_URL}/functions/${function_name}/${function_revision}; echo ""
}

if [[ "$1" == "func" ]]; then

  if [[ "$2" == "help" ]]; then
    echo "🚧 work in progress"
    exit 0
  fi

  if [[ "$2" == "list" ]]; then
    curl ${PROCYON_URL}/functions
    exit 0
  fi

  if [[ "$2" == "post" ]]; then
    function_name=$3
    data=$4
    procyon_func_post ${function_name} ${data}
    exit 0
  fi

  if [[ "$2" == "post-revision" ]]; then
    function_name=$3
    function_revision=$4
    data=$5
    procyon_func_post_rev ${function_name} ${function_revision} ${data} 
    exit 0
  fi

  if [[ "$2" == "get" ]]; then
    function_name=$3
    procyon_func_get ${function_name}
    exit 0
  fi

  if [[ "$2" == "get-revision" ]]; then
    function_name=$3
    function_revision=$4
    procyon_func_get_rev ${function_name} ${function_revision}
    exit 0
  fi

  echo "🤔 please try again, I don't understand"
fi
