# 🚧 this is a work in progress

# only for use with the Procyon Registry
# (it's for testing)
procyon-registry:
  url: https://localhost:7070

procyon-launcher:
  url: http://localhost:9090
  # protect the procyon launcher API
  admin-token: "ilovepandas"
  #admin-token: "ilovetigers"

procyon-reverse:
  url: https://localhost:4443
  #url: http://localhost:8080

