name: Release Procyon binaries

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Procyon Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./"
          binary_name: "procyon"
          ldflags: "-s -w"
          extra_files: LICENSE README.txt procyon.json ./samples/hello/hello.wasm
      - uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./alcor-reverse-proxy"
          binary_name: "alcor"
          ldflags: "-s -w"
          extra_files: LICENSE README.txt alcor.json
      - uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./venusia-registry"
          binary_name: "venusia"
          ldflags: "-s -w"
          extra_files: LICENSE README.txt
