name: Release Procyon binaries

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Procyon Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./"
          binary_name: "procyon"
          ldflags: "-s -w"
          extra_files: procyon.json ./procyonctl/procyonctl ./procyonctl/procyon.config
      - uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./procyon-reverse-proxy"
          binary_name: "procyon-reverse"
          ldflags: "-s -w"
          extra_files: ./procyon-reverse-proxy/procyon.json
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: ./procyon-registry
          dest: procyon-registry.zip
